version: '3.7'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    healthcheck:
          test: [ "CMD", "mongo", "--eval", "db.stats()" ]
          interval: 10s
          timeout: 5s
          retries: 3

volumes:
  mongodb_data_container: